server: 
  port: 8080
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: APIGateWayService
 cloud:
    gateway:
      routes:
      - id: CityAdminModule
        uri: http://localhost:8089/
        predicates:
        - Path=/city/ad/**
      - id: CityCustomerModule
        uri: http://localhost:8084/
        predicates:
        - Path=/city/cu/**
      - id: SiteAdminModule
        uri: http://localhost:8085/
        predicates:
        - Path=/site/ad/**
      - id: SiteCustomerModule
        uri: http://localhost:8086/
        predicates:
        - Path=/site/cu/**
      - id: HotelAdminModule
        uri: http://localhost:8087/
        predicates:
        - Path=/hotel/ad/**
      - id: HotelCustomerModule
        uri: http://localhost:8088/
        predicates:
        - Path=/hotel/cu/**
      - id: HeritageTourJWTService
        uri: http://localhost:8081/
        predicates:
        - Path=/api/jwt/**
      