jwt:
  secret: secrectkey123

server:
    port: 8081         
    
    
spring:
    application:
           name: HeritageTourJWTService
    data:
        mongodb:
               uri: mongodb+srv://abhishekbansod01:Mongodatabase@cluster0.pzw34.mongodb.net/HeritageTourUsersdb?retryWrites=true&w=majority

eureka:
     client:
          service-url:
                   defaultZone: http://localhost:8761/eureka/          

    
data:
   exception:
          incmsg: Invalid Credentials!!
            